version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/oj
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
    depends_on:
      - mongo
      - redis

  compiler:
    build: ./compiler
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  mongo_data:
