services:
  - type: web
    name: codester-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: COMPILER_SERVICE_URL
        value: https://your-compiler-ec2-instance.com
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app 